# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build the project

on:
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  buildAndComment:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: project.jar
      ARTIFACT_PATH: ./staging
    permissions:
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -U
      
    - run: mkdir staging && cp target/*-with-dependencies.jar ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }}
    - name: Upload Artifact
      id: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}/${{ env.ARTIFACT_NAME }}
        if-no-files-found: error

    - name: Update Comment
      if: ${{ success() }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |-
          ## Build Preview
          
          [![badge]](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          You can find files attached to the below linked Workflow Run URL (Logs).
          
          Please note that files only stay for around 90 days!

          | Name      | Link                                                                                |
          |-----------|-------------------------------------------------------------------------------------|
          | Commit    | ${{ github.event.pull_request.head.sha }}                                           |
          | Logs      | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
          | Jar Files | ${{ steps.upload-artifacts.outputs.artifact-url }}                                  |
          
          [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge
          
    - name: Update Comment
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |-
          ## Build Preview
          
          [![badge]](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          There was an issue generating the Jar files from your Pull request.
          Please review the logs linked below for further information.
          
          | Name   | Link                                                                                |
          |--------|-------------------------------------------------------------------------------------|
          | Commit | ${{ github.event.pull_request.head.sha }}                                           |
          | Logs   | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
          
          [badge]: https://img.shields.io/badge/Build-Failure!-f85149?logo=github&style=for-the-badge
